name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y \
            openjdk-17-jdk \
            zip unzip \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            git \
            libffi-dev \
            libssl-dev \
            libncurses5 \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev

      - name: Install Cython & Buildozer
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: connectgold-apk
          path: bin/*.apk
