name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git libffi-dev libssl-dev

      - name: Install Cython & Buildozer
        run: |
          pip install cython
          pip install buildozer

      - name: Set up Android SDK & NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget https://github.com/kivy/buildozer/releases/download/v1.5.0/android-sdk.zip
          unzip android-sdk.zip
          rm android-sdk.zip

      - name: Build APK
        env:
          ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: connectgold-apk
          path: bin/*.apk
