name: Build Flutter APK

on:
  push:
    branches:
      - main  # 👈 change if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get
        working-directory: connectgold_app

      - name: Build APK
        run: flutter build apk --release
        working-directory: connectgold_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: connectgold_app/build/app/outputs/flutter-apk/app-release.apk
